jobs:
- name: grep-analysis
  serial: true
  plan:
  - get: apollo-source-code
    trigger: true
  - get: analysis-result
    trigger: false
  - task: check
    file: analysis-result/ci/check-task.yml
  - put: analysis-result
    params:
      repository: new-result

resources:
- name: apollo-source-code
  type: git
  check_every: 60m
  source:
    uri: https://github.com/ApolloAuto/apollo.git
    branch: master
- name: analysis-result
  type: git
  source:
    uri: git@github.com:drchangliu/privacywatch.git
    branch: master
    private_key: ((git-private-key))
    username: ((git-username))
